# Results 64

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("results_64_3layers.csv")
# df = pd.read_csv("results_64_2.csv")
# df = df.iloc[50:].reset_index(drop=True)

In [3]:
df.head(3)

,epoch,acc,loss,precision,recall,val_acc,val_loss,val_precision,val_recall
0,0,0.887319,0.266820,0.909006,0.953197,0.728274,1.007201,0.694868,0.996024
1,1,0.961704,0.103176,0.970006,0.982031,0.847613,0.456001,0.804996,0.993042
2,2,0.975058,0.073083,0.980113,0.988578,0.878213,0.362413,0.838223,0.994036

In [4]:
df.tail(3)

,epoch,acc,loss,precision,recall,val_acc,val_loss,val_precision,val_recall
47,47,0.997682,0.005743,0.998190,0.998886,0.872093,0.616662,0.834593,0.988072
48,48,0.998124,0.005792,0.998886,0.998746,0.848225,0.760175,0.806634,0.991054
49,49,0.997903,0.005474,0.998746,0.998607,0.791922,1.122967,0.750753,0.991054

# Inference 64

In [5]:
from ultralytics import YOLO

In [6]:
path = "../datasets/haris/images/val"

images = [
    f"{path}/ds_1__Scene4_11.png",
    # f"{path}/ds_1__Scene4_30.png",
    # f"{path}/ds_5__ABmframe00127.jpg",
    # f"{path}/ds_5__monedero_1198.JPG",
    # f"{path}/ds_5__monedero_1231.JPG",
    # f"{path}/ds_6__amfin1033_jpg.rf.543b1deb9df7281651effbea53b3d991.jpg",
]

## Pretrained YOLO 26

In [7]:
model = YOLO("yolo26n.pt")  # best.pt
results = model(images)
for r in results: r.show()

0: 640x448 1 person, 1 car, 168.2ms
Speed: 4.1ms preprocess, 168.2ms inference, 9.4ms postprocess per image at shape (1, 3, 640, 448)

In [8]:
df.head()

,epoch,acc,loss,precision,recall,val_acc,val_loss,val_precision,val_recall
0,0,0.887319,0.266820,0.909006,0.953197,0.728274,1.007201,0.694868,0.996024
1,1,0.961704,0.103176,0.970006,0.982031,0.847613,0.456001,0.804996,0.993042
2,2,0.975058,0.073083,0.980113,0.988578,0.878213,0.362413,0.838223,0.994036
3,3,0.979914,0.055521,0.984624,0.990110,0.848837,0.464285,0.805310,0.995030
4,4,0.985101,0.043126,0.988353,0.992896,0.894737,0.314648,0.865149,0.982107

# YOLO Models Results

In [9]:
def get_metrics(filename, model_name):
    df = pd.read_csv(filename)
    # idx = df["metrics/mAP50(B)"].idxmax()
    # idx = df["metrics/precision(B)"].idxmax()
    idx = df["metrics/mAP50-95(B)"].idxmax()
    
    precision = df.loc[idx, "metrics/precision(B)"]
    recall = df.loc[idx, "metrics/recall(B)"]
    map50 = df.loc[idx, "metrics/mAP50(B)"]
    map50_95 = df.loc[idx, "metrics/mAP50-95(B)"]

    print(model_name)
    print(f"Idx: {idx}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"mAP50: {map50}")
    print(f"mAP50-95: {map50_95}")
    print("")

    return precision, recall, map50, map50_95

a = get_metrics("results_yolo5nu.csv", "YOLO 5n")
b = get_metrics("results_8n.csv", "YOLO 8n")
c = get_metrics("results_11n.csv", "YOLO 11n")
d = get_metrics("results_26n.csv", "YOLO 26n")

YOLO 5n
Idx: 144
Precision: 0.85343
Recall: 0.80088
mAP50: 0.8391
mAP50-95: 0.52136

YOLO 8n
Idx: 124
Precision: 0.86054
Recall: 0.78959
mAP50: 0.84415
mAP50-95: 0.5229

YOLO 11n
Idx: 148
Precision: 0.84396
Recall: 0.80371
mAP50: 0.84215
mAP50-95: 0.53631

YOLO 26n
Idx: 98
Precision: 0.86609
Recall: 0.77099
mAP50: 0.83411
mAP50-95: 0.53751

In [10]:
# Benchmarks kaggle HARIS

# Metric 	    Overall 	Gun 	Knife
# Precision 	87.2% 	    86.4% 	88.0%
# Recall 	    70.4% 	    74.1% 	66.7%
# mAP50 	    78.0% 	    80.2% 	75.9%
# mAP50-95 	    47.6% 	    56.2% 	39.0%

# RESNET50

In [11]:
def get_resnet_metrics(filename, model_name):
    df = pd.read_csv(filename)
    idx = df["val_loss"].idxmin()
    
    precision = df.loc[idx, "val_precision"]
    recall = df.loc[idx, "val_recall"]
    accuracy = df.loc[idx, "val_acc"]

    print(model_name)
    print(f"Index: {idx}")
    print(f"Accuracy: {accuracy}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print("")

    return precision, recall

a = get_resnet_metrics("results_1.csv", "RESNET50 Fine tune last conv")
b = get_resnet_metrics("results_64_3layers.csv", "RESNET50 Fine tune last 3 conv")

RESNET50 Fine tune last conv
Index: 51
Accuracy: 0.9418604373931884
Precision: 0.9317535758018494
Recall: 0.9771371483802797

RESNET50 Fine tune last 3 conv
Index: 6
Accuracy: 0.9167686700820924
Precision: 0.89402174949646
Recall: 0.9811133146286012

In [12]:
df.head(3)

,epoch,acc,loss,precision,recall,val_acc,val_loss,val_precision,val_recall
0,0,0.887319,0.266820,0.909006,0.953197,0.728274,1.007201,0.694868,0.996024
1,1,0.961704,0.103176,0.970006,0.982031,0.847613,0.456001,0.804996,0.993042
2,2,0.975058,0.073083,0.980113,0.988578,0.878213,0.362413,0.838223,0.994036

# Confusion Matrix: Classification Conversion

- weapon: gun or knife
- no weapon: background

- TP: predicted weapon AND true weapon
- FP: predicted weapon BUT true background
- FN: predicted background BUT true weapon
- TN: predicted background AND true background

- Precision = TP / (TP + FP)
- Recall = TP / (TP + FN)

In [13]:
def get_precision(TP, FP): 
    return TP / (TP + FP)
def get_recall(TP, FN): 
    return TP / (TP + FN)
def get_accuracy(TP, TN, FP, FN): 
    return (TP + TN) / (TP + TN + FP + FN)

In [14]:
validation_size = 1800

# right up: yolo 5
print("yolo v5nu")
TP = (689+1+3+294)
FP = (216+80)
FN = (194+27)
TN = validation_size - (TP + FP + FN)
P = get_precision(TP, FP)
R = get_recall(TP, FN)
A = get_accuracy(TP, TN, FP, FN)
print(f"Accuracy: {A}")
print(f"Precision: {P}")
print(f"Recall: {R}")
print()

# right down: yolo 8
print("yolo 8n")
TP = (691+2+6+297)
FP = (208+74)
FN = (189+23)
TN = validation_size - (TP + FP + FN)
P = get_precision(TP, FP)
R = get_recall(TP, FN)
A = get_accuracy(TP, TN, FP, FN)
print(f"Accuracy: {A}")
print(f"Precision: {P}")
print(f"Recall: {R}")
print()

# left down: yolo 11
print("yolo 11n")
TP = (699+1+2+296)
FP = (218+69)
FN = (185+25)
TN = validation_size - (TP + FP + FN)
P = get_precision(TP, FP)
R = get_recall(TP, FN)
A = get_accuracy(TP, TN, FP, FN)
print(f"Accuracy: {A}")
print(f"Precision: {P}")
print(f"Recall: {R}")
print()

# left up: yolo 26
print("yolo 26n")
TP = (658+1+6+297)
FN = (159+49)
FP = (222+24)
TN = validation_size - (TP + FP + FN)
P = get_precision(TP, FP)
R = get_recall(TP, FN)
A = get_accuracy(TP, TN, FP, FN)
print(f"Accuracy: {A}")
print(f"Precision: {P}")
print(f"Recall: {R}")
print()

yolo v5nu
Accuracy: 0.7127777777777777
Precision: 0.769290724863601
Recall: 0.8170529801324503

yolo 8n
Accuracy: 0.7255555555555555
Precision: 0.7793427230046949
Recall: 0.8245033112582781

yolo 11n
Accuracy: 0.7238888888888889
Precision: 0.7766536964980545
Recall: 0.8261589403973509

yolo 26n
Accuracy: 0.7477777777777778
Precision: 0.7963576158940397
Recall: 0.8222222222222222

feh WARNING: /tmp/.X0-lock - Does not look like an image (magic bytes missing)
feh WARNING: /tmp/serverauth.fXjGs4TKe2 - Does not look like an image (magic bytes missing)